apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: backend-fargate
  template:
    metadata:
      labels:
        app: backend-fargate
