apiVersion: v1
kind: Service
metadata:
  name: django-backend
  namespace : default
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
spec:
  selector:
    app: backend-fargate
