---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-fargate
  template:
    metadata:
      labels:
        app: backend-fargate
    spec:
      containers:
        - name: django-backend
          image: public.ecr.aws/nginx/nginx:1.21
          imagePullPolicy: Always
          ports:
            - containerPort: 80
